CREATE TABLE IF NOT EXISTS T_BAC (
  course_code      CHAR(2)      NOT NULL COMMENT '場コード',
  year_code        CHAR(2)      NOT NULL COMMENT '年',
  kai              CHAR(1)      NOT NULL COMMENT '回',
  day_code         CHAR(1)      NOT NULL COMMENT '日',
  race_num         CHAR(2)      NOT NULL COMMENT 'R',
  ymd              CHAR(8)               COMMENT '年月日',
  start_time       CHAR(4)               COMMENT '発走時間',
  distance         CHAR(4)               COMMENT '距離',
  tds_code         CHAR(1)               COMMENT '芝ダ障害コード',
  migihidari       CHAR(1)               COMMENT '右左',
  naigai           CHAR(1)               COMMENT '内外',
  syubetsu         CHAR(2)               COMMENT '種別',
  class            CHAR(2)               COMMENT '条件',
  kigou            CHAR(3)               COMMENT '記号',
  weight           CHAR(1)               COMMENT '重量',
  grade            CHAR(1)               COMMENT 'グレード',
  race_name        VARCHAR(50)           COMMENT 'レース名',
  kaisu            CHAR(8)               COMMENT '回数',
  heads            CHAR(2)               COMMENT '頭数',
  course_abcd      CHAR(1)               COMMENT 'コース',
  kaisai_kubun     CHAR(1)               COMMENT '開催区分',
  race_name_short  CHAR(8)               COMMENT 'レース名短縮',
  race_name_9char  VARCHAR(18)           COMMENT 'レース名9文字',
  data_kubun       CHAR(1)               COMMENT 'データ区分',
  prize_1st        CHAR(5)               COMMENT '1着賞金',
  prize_2nd        CHAR(5)               COMMENT '2着賞金',
  prize_3rd        CHAR(5)               COMMENT '3着賞金',
  prize_4th        CHAR(5)               COMMENT '4着賞金',
  prize_5th        CHAR(5)               COMMENT '5着賞金',
  prize_1st_calc   CHAR(5)               COMMENT '1着算入賞金',
  prize_2nd_calc   CHAR(5)               COMMENT '2着算入賞金',
  baken_flag       CHAR(16)              COMMENT '馬券発売フラグ',
  win5_flag        CHAR(1)               COMMENT 'WIN5フラグ',
  load_file        VARCHAR(20)           COMMENT 'ロードファイル',
  last_update      VARCHAR(20)           COMMENT '最終更新',
  PRIMARY KEY (course_code, year_code, kai, day_code, race_num)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='BACレース基本情報';
