CREATE TABLE IF NOT EXISTS T_CYB (
  course_code            CHAR(2)      NOT NULL COMMENT '場コード',
  year_code              CHAR(2)      NOT NULL COMMENT '年',
  kai                    CHAR(1)      NOT NULL COMMENT '回',
  day_code               CHAR(1)      NOT NULL COMMENT '日',
  race_num               CHAR(2)      NOT NULL COMMENT 'R',
  uma_num                CHAR(2)      NOT NULL COMMENT '馬番',
  chokyo_type            CHAR(2)               COMMENT '調教タイプ',
  chokyo_course_type     CHAR(1)               COMMENT '調教コース種別',
  course_saka            CHAR(2)               COMMENT '坂',
  course_w               CHAR(2)               COMMENT 'W',
  course_da              CHAR(2)               COMMENT 'ダ',
  course_shiba           CHAR(2)               COMMENT '芝',
  course_pool            CHAR(2)               COMMENT 'プール',
  course_sho             CHAR(2)               COMMENT '障',
  course_poly            CHAR(2)               COMMENT 'ポリトラック',
  chokyo_kyori           CHAR(1)               COMMENT '調教距離',
  chokyo_juten           CHAR(1)               COMMENT '調教重点',
  oi_index               CHAR(3)               COMMENT '追切指数',
  shiage_index           CHAR(3)               COMMENT '仕上指数',
  chokyo_ryo_hyoka       CHAR(1)               COMMENT '調教量評価',
  shiage_index_henka     CHAR(1)               COMMENT '仕上指数変化',
  chokyo_comment         VARCHAR(40)           COMMENT '調教コメント',
  comment_ymd            CHAR(8)               COMMENT 'コメント年月日',
  chokyo_hyoka           CHAR(1)               COMMENT '調教評価',
  isshuumae_oi_index     CHAR(3)               COMMENT '一週前追切指数',
  isshuumae_oi_course    CHAR(2)               COMMENT '一週前追切コース',
  load_file              VARCHAR(20)           COMMENT 'ロードファイル',
  last_update            VARCHAR(20)           COMMENT '最終更新',
  PRIMARY KEY (course_code, year_code, kai, day_code, race_num, uma_num)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='CYB調教分析';
