CREATE TABLE IF NOT EXISTS T_HJC (
  course_code      CHAR(2)      NOT NULL COMMENT '場コード',
  year_code        CHAR(2)      NOT NULL COMMENT '年',
  kai              CHAR(1)      NOT NULL COMMENT '回',
  day_code         CHAR(1)      NOT NULL COMMENT '日（16進数）',
  race_num         CHAR(2)      NOT NULL COMMENT 'R',
  tansho_umaban_1      CHAR(6), tansho_payout_1      CHAR(9),
  tansho_umaban_2      CHAR(6), tansho_payout_2      CHAR(9),
  tansho_umaban_3      CHAR(6), tansho_payout_3      CHAR(9),
  fukusho_umaban_1     CHAR(6), fukusho_payout_1     CHAR(9),
  fukusho_umaban_2     CHAR(6), fukusho_payout_2     CHAR(9),
  fukusho_umaban_3     CHAR(6), fukusho_payout_3     CHAR(9),
  fukusho_umaban_4     CHAR(6), fukusho_payout_4     CHAR(9),
  fukusho_umaban_5     CHAR(6), fukusho_payout_5     CHAR(9),
  wakuren_umaban_1     CHAR(6), wakuren_payout_1     CHAR(9),
  wakuren_umaban_2     CHAR(6), wakuren_payout_2     CHAR(9),
  wakuren_umaban_3     CHAR(6), wakuren_payout_3     CHAR(9),
  umaren_umaban_1      CHAR(6), umaren_payout_1      CHAR(9),
  umaren_umaban_2      CHAR(6), umaren_payout_2      CHAR(9),
  umaren_umaban_3      CHAR(6), umaren_payout_3      CHAR(9),
  wide_umaban_1        CHAR(6), wide_payout_1        CHAR(9),
  wide_umaban_2        CHAR(6), wide_payout_2        CHAR(9),
  wide_umaban_3        CHAR(6), wide_payout_3        CHAR(9),
  wide_umaban_4        CHAR(6), wide_payout_4        CHAR(9),
  wide_umaban_5        CHAR(6), wide_payout_5        CHAR(9),
  wide_umaban_6        CHAR(6), wide_payout_6        CHAR(9),
  wide_umaban_7        CHAR(6), wide_payout_7        CHAR(9),
  umatan_umaban_1      CHAR(6), umatan_payout_1      CHAR(9),
  umatan_umaban_2      CHAR(6), umatan_payout_2      CHAR(9),
  umatan_umaban_3      CHAR(6), umatan_payout_3      CHAR(9),
  umatan_umaban_4      CHAR(6), umatan_payout_4      CHAR(9),
  umatan_umaban_5      CHAR(6), umatan_payout_5      CHAR(9),
  umatan_umaban_6      CHAR(6), umatan_payout_6      CHAR(9),
  sanrenpuku_umaban_1  CHAR(6), sanrenpuku_payout_1  CHAR(9),
  sanrenpuku_umaban_2  CHAR(6), sanrenpuku_payout_2  CHAR(9),
  sanrenpuku_umaban_3  CHAR(6), sanrenpuku_payout_3  CHAR(9),
  sanrentan_umaban_1   CHAR(6), sanrentan_payout_1   CHAR(9),
  sanrentan_umaban_2   CHAR(6), sanrentan_payout_2   CHAR(9),
  sanrentan_umaban_3   CHAR(6), sanrentan_payout_3   CHAR(9),
  sanrentan_umaban_4   CHAR(6), sanrentan_payout_4   CHAR(9),
  sanrentan_umaban_5   CHAR(6), sanrentan_payout_5   CHAR(9),
  sanrentan_umaban_6   CHAR(6), sanrentan_payout_6   CHAR(9),
  load_file        VARCHAR(20)           COMMENT 'ロードファイル',
  last_update      VARCHAR(20)           COMMENT '最終更新',
  PRIMARY KEY (course_code, year_code, kai, day_code, race_num)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='HJC払戻データ';
