CREATE TABLE IF NOT EXISTS T_KYI (
  -- レースキー + 馬番 で一意
  course_code           CHAR(2)      NOT NULL COMMENT '場コード',
  year_code             CHAR(2)      NOT NULL COMMENT '年',
  kai                   CHAR(1)      NOT NULL COMMENT '回',
  day_code              CHAR(1)      NOT NULL COMMENT '日',
  race_num              CHAR(2)      NOT NULL COMMENT 'R',
  uma_num               CHAR(2)      NOT NULL COMMENT '馬番',
  -- 基本情報
  blood_reg_num         CHAR(8)               COMMENT '血統登録番号',
  uma_name              VARCHAR(36)           COMMENT '馬名',
  -- 指数情報
  idm                   CHAR(5)               COMMENT 'IDM',
  kishu_index           CHAR(5)               COMMENT '騎手指数',
  joho_index            CHAR(5)               COMMENT '情報指数',
  sogo_index            CHAR(5)               COMMENT '総合指数',
  -- 馬質情報
  kyakushitsu           CHAR(1)               COMMENT '脚質',
  kyori_tekisei         CHAR(1)               COMMENT '距離適性',
  joshodo               CHAR(1)               COMMENT '上昇度',
  rotation              CHAR(3)               COMMENT 'ローテーション',
  -- オッズ・人気
  kijun_odds            CHAR(5)               COMMENT '基準オッズ',
  kijun_ninki           CHAR(2)               COMMENT '基準人気順位',
  kijun_fukusho_odds    CHAR(5)               COMMENT '基準複勝オッズ',
  kijun_fukusho_ninki   CHAR(2)               COMMENT '基準複勝人気順位',
  -- 専門紙印数
  tokutei_honmei        CHAR(3)               COMMENT '特定◎',
  tokutei_taikou        CHAR(3)               COMMENT '特定○',
  tokutei_tanana        CHAR(3)               COMMENT '特定▲',
  tokutei_rengai        CHAR(3)               COMMENT '特定△',
  tokutei_batsu         CHAR(3)               COMMENT '特定×',
  sogo_honmei           CHAR(3)               COMMENT '総合◎',
  sogo_taikou           CHAR(3)               COMMENT '総合○',
  sogo_tanana           CHAR(3)               COMMENT '総合▲',
  sogo_rengai           CHAR(3)               COMMENT '総合△',
  sogo_batsu            CHAR(3)               COMMENT '総合×',
  -- その他指数
  ninki_index           CHAR(5)               COMMENT '人気指数',
  chokyo_index          CHAR(5)               COMMENT '調教指数',
  kyusha_index          CHAR(5)               COMMENT '厩舎指数',
  -- 第3版
  chokyo_yajirushi      CHAR(1)               COMMENT '調教矢印コード',
  kyusha_hyoka          CHAR(1)               COMMENT '厩舎評価コード',
  kishu_renntai_rate    CHAR(4)               COMMENT '騎手期待連対率',
  gekiso_index          CHAR(3)               COMMENT '激走指数',
  hizume_code           CHAR(2)               COMMENT '蹄コード',
  omo_tekisei           CHAR(1)               COMMENT '重適正コード',
  class_code            CHAR(2)               COMMENT 'クラスコード',
  -- 第4版
  blinker               CHAR(1)               COMMENT 'ブリンカー',
  kishu_name            VARCHAR(12)           COMMENT '騎手名',
  futan_juryo           CHAR(3)               COMMENT '負担重量',
  minarai_kubun         CHAR(1)               COMMENT '見習い区分',
  trainer_name          VARCHAR(12)           COMMENT '調教師名',
  trainer_belong        CHAR(4)               COMMENT '調教師所属',
  -- 前走リンクキー
  prev1_seiseki_key     CHAR(16)              COMMENT '前走1競走成績キー',
  prev2_seiseki_key     CHAR(16)              COMMENT '前走2競走成績キー',
  prev3_seiseki_key     CHAR(16)              COMMENT '前走3競走成績キー',
  prev4_seiseki_key     CHAR(16)              COMMENT '前走4競走成績キー',
  prev5_seiseki_key     CHAR(16)              COMMENT '前走5競走成績キー',
  prev1_race_key        CHAR(8)               COMMENT '前走1レースキー',
  prev2_race_key        CHAR(8)               COMMENT '前走2レースキー',
  prev3_race_key        CHAR(8)               COMMENT '前走3レースキー',
  prev4_race_key        CHAR(8)               COMMENT '前走4レースキー',
  prev5_race_key        CHAR(8)               COMMENT '前走5レースキー',
  waku_num              CHAR(1)               COMMENT '枠番',
  -- 第5版（印コード）
  in_sogo               CHAR(1)               COMMENT '総合印',
  in_idm                CHAR(1)               COMMENT 'IDM印',
  in_joho               CHAR(1)               COMMENT '情報印',
  in_kishu              CHAR(1)               COMMENT '騎手印',
  in_kyusha             CHAR(1)               COMMENT '厩舎印',
  in_chokyo             CHAR(1)               COMMENT '調教印',
  in_gekiso             CHAR(1)               COMMENT '激走印',
  shiba_tekisei         CHAR(1)               COMMENT '芝適性コード',
  dirt_tekisei          CHAR(1)               COMMENT 'ダ適性コード',
  kishu_code            CHAR(5)               COMMENT '騎手コード',
  trainer_code          CHAR(5)               COMMENT '調教師コード',
  -- 第6版
  prize_earned          CHAR(6)               COMMENT '獲得賞金',
  prize_shu             CHAR(5)               COMMENT '収得賞金',
  joken_class           CHAR(1)               COMMENT '条件クラス',
  ten_index             CHAR(5)               COMMENT 'テン指数',
  pace_index            CHAR(5)               COMMENT 'ペース指数',
  agari_index           CHAR(5)               COMMENT '上がり指数',
  ichi_index            CHAR(5)               COMMENT '位置指数',
  pace_yoso             CHAR(1)               COMMENT 'ペース予想',
  michunaka_juni        CHAR(2)               COMMENT '道中順位',
  michunaka_sa          CHAR(2)               COMMENT '道中差',
  michunaka_naigai      CHAR(1)               COMMENT '道中内外',
  ato3f_juni            CHAR(2)               COMMENT '後3F順位',
  ato3f_sa              CHAR(2)               COMMENT '後3F差',
  ato3f_naigai          CHAR(1)               COMMENT '後3F内外',
  goal_juni             CHAR(2)               COMMENT 'ゴール順位',
  goal_sa               CHAR(2)               COMMENT 'ゴール差',
  goal_naigai           CHAR(1)               COMMENT 'ゴール内外',
  tenkai_kigo           CHAR(1)               COMMENT '展開記号',
  -- 第6a版
  kyori_tekisei2        CHAR(1)               COMMENT '距離適性2',
  waku_weight           CHAR(3)               COMMENT '枠確定馬体重',
  waku_weight_diff      CHAR(3)               COMMENT '枠確定馬体重増減',
  -- 第7版
  torikeshi_flag        CHAR(1)               COMMENT '取消フラグ',
  seibetsu_code         CHAR(1)               COMMENT '性別コード',
  umanushi_name         VARCHAR(40)           COMMENT '馬主名',
  umanushi_code         CHAR(2)               COMMENT '馬主会コード',
  uma_kigo_code         CHAR(2)               COMMENT '馬記号コード',
  gekiso_juni           CHAR(2)               COMMENT '激走順位',
  ls_index_juni         CHAR(2)               COMMENT 'LS指数順位',
  ten_index_juni        CHAR(2)               COMMENT 'テン指数順位',
  pace_index_juni       CHAR(2)               COMMENT 'ペース指数順位',
  agari_index_juni      CHAR(2)               COMMENT '上がり指数順位',
  ichi_index_juni       CHAR(2)               COMMENT '位置指数順位',
  -- 第8版
  kishu_tansho_rate     CHAR(4)               COMMENT '騎手期待単勝率',
  kishu_3uchi_rate      CHAR(4)               COMMENT '騎手期待3着内率',
  yuso_kubun            CHAR(1)               COMMENT '輸送区分',
  -- 第9版
  soho                  CHAR(8)               COMMENT '走法',
  taigata               CHAR(24)              COMMENT '体型',
  taigata_sogo1         CHAR(3)               COMMENT '体型総合1',
  taigata_sogo2         CHAR(3)               COMMENT '体型総合2',
  taigata_sogo3         CHAR(3)               COMMENT '体型総合3',
  uma_tokki1            CHAR(3)               COMMENT '馬特記1',
  uma_tokki2            CHAR(3)               COMMENT '馬特記2',
  uma_tokki3            CHAR(3)               COMMENT '馬特記3',
  uma_start_index       CHAR(4)               COMMENT '馬スタート指数',
  uma_okure_rate        CHAR(4)               COMMENT '馬出遅率',
  sankosaki_mae         CHAR(2)               COMMENT '参考前走',
  sankosaki_kishu_code  CHAR(5)               COMMENT '参考前走騎手コード',
  manbaken_index        CHAR(3)               COMMENT '万券指数',
  manbaken_in           CHAR(1)               COMMENT '万券印',
  -- 第10版
  kokyuu_flag           CHAR(1)               COMMENT '降級フラグ',
  gekiso_type           CHAR(2)               COMMENT '激走タイプ',
  kyuyo_riyuu_code      CHAR(2)               COMMENT '休養理由分類コード',
  -- 第11版
  flag                  CHAR(16)              COMMENT 'フラグ',
  nyukyu_hashiri        CHAR(2)               COMMENT '入厩何走目',
  nyukyu_ymd            CHAR(8)               COMMENT '入厩年月日',
  nyukyu_nichi_mae      CHAR(3)               COMMENT '入厩何日前',
  hohbokusaki           VARCHAR(50)           COMMENT '放牧先',
  hohbokusaki_rank      CHAR(1)               COMMENT '放牧先ランク',
  kyusha_rank           CHAR(1)               COMMENT '厩舎ランク',
  -- 管理
  load_file             VARCHAR(20)           COMMENT 'ロードファイル',
  last_update           VARCHAR(20)           COMMENT '最終更新',
  PRIMARY KEY (course_code, year_code, kai, day_code, race_num, uma_num)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='KYI出馬表';
