CREATE TABLE IF NOT EXISTS T_SED (
  course_code        CHAR(2)      NOT NULL COMMENT '場コード',
  year_code          CHAR(2)      NOT NULL COMMENT '年',
  kai                CHAR(1)      NOT NULL COMMENT '回',
  day_code           CHAR(1)      NOT NULL COMMENT '日',
  race_num           CHAR(2)      NOT NULL COMMENT 'R',
  umaban             CHAR(2)      NOT NULL COMMENT '馬番',
  blood_num          CHAR(8)               COMMENT '血統登録番号',
  ymd                CHAR(8)               COMMENT '年月日',
  horse_name         VARCHAR(36)           COMMENT '馬名',
  distance           CHAR(4)               COMMENT '距離',
  tds_code           CHAR(1)               COMMENT '芝ダ障害コード',
  migihidari         CHAR(1)               COMMENT '右左',
  naigai             CHAR(1)               COMMENT '内外',
  baba_cond          CHAR(2)               COMMENT '馬場状態',
  syubetsu           CHAR(2)               COMMENT '種別',
  class              CHAR(2)               COMMENT '条件',
  kigou              CHAR(3)               COMMENT '記号',
  weight             CHAR(1)               COMMENT '重量',
  grade              CHAR(1)               COMMENT 'グレード',
  race_name          VARCHAR(50)           COMMENT 'レース名',
  heads              CHAR(2)               COMMENT '頭数',
  race_name_ryaku    CHAR(8)               COMMENT 'レース名略称',
  order_of_finish    CHAR(2)               COMMENT '着順',
  ijou_kubun         CHAR(1)               COMMENT '異常区分',
  finish_time        CHAR(4)               COMMENT 'タイム',
  kinryou            CHAR(3)               COMMENT '斤量',
  jockey_name        VARCHAR(12)           COMMENT '騎手名',
  trainer_name       VARCHAR(12)           COMMENT '調教師名',
  win_odds           CHAR(6)               COMMENT '確定単勝オッズ',
  win_odds_rank      CHAR(2)               COMMENT '確定単勝人気順位',
  idm                CHAR(3)               COMMENT 'IDM',
  soten              CHAR(3)               COMMENT '素点',
  baba_diff          CHAR(3)               COMMENT '馬場差',
  pace               CHAR(3)               COMMENT 'ペース',
  deokure            CHAR(3)               COMMENT '出遅',
  ichidori           CHAR(3)               COMMENT '位置取',
  furi               CHAR(3)               COMMENT '不利',
  mae_furi           CHAR(3)               COMMENT '前不利',
  naka_furi          CHAR(3)               COMMENT '中不利',
  ushiro_furi        CHAR(3)               COMMENT '後不利',
  race               CHAR(3)               COMMENT 'レース',
  course_posi        CHAR(1)               COMMENT 'コース取り',
  up_code            CHAR(1)               COMMENT '上昇度コード',
  class_code         CHAR(2)               COMMENT 'クラスコード',
  batai_code         CHAR(1)               COMMENT '馬体コード',
  kehai_code         CHAR(1)               COMMENT '気配コード',
  race_pace          CHAR(1)               COMMENT 'レースペース',
  horse_pace         CHAR(1)               COMMENT '馬ペース',
  first_half_idx     CHAR(5)               COMMENT 'テン指数',
  latter_half_idx    CHAR(5)               COMMENT '上がり指数',
  pace_idx           CHAR(5)               COMMENT 'ペース指数',
  race_pace_idx      CHAR(5)               COMMENT 'レースP指数',
  win_horse_name     VARCHAR(12)           COMMENT '1(2)着馬名',
  win_diff           CHAR(3)               COMMENT '1(2)着タイム差',
  first_half_time    CHAR(3)               COMMENT '前3F',
  latter_half_time   CHAR(3)               COMMENT '後3F',
  place_odds         CHAR(6)               COMMENT '確定複勝オッズ下',
  win_odds_10        CHAR(6)               COMMENT '10時単勝オッズ',
  place_odds_10      CHAR(6)               COMMENT '10時複勝オッズ',
  corner_1           CHAR(2)               COMMENT 'コーナー順位1',
  corner_2           CHAR(2)               COMMENT 'コーナー順位2',
  corner_3           CHAR(2)               COMMENT 'コーナー順位3',
  corner_4           CHAR(2)               COMMENT 'コーナー順位4',
  first_half_diff    CHAR(3)               COMMENT '前3F先頭差',
  latter_half_diff   CHAR(3)               COMMENT '後3F先頭差',
  jockey_code        CHAR(5)               COMMENT '騎手コード',
  trainer_code       CHAR(5)               COMMENT '調教師コード',
  horse_weight       CHAR(3)               COMMENT '馬体重',
  horse_weight_diff  CHAR(3)               COMMENT '馬体重増減',
  weather_code       CHAR(1)               COMMENT '天候コード',
  course_abcd        CHAR(1)               COMMENT 'コース',
  race_kyakushitsu   CHAR(1)               COMMENT 'レース脚質',
  win                CHAR(7)               COMMENT '単勝',
  place              CHAR(7)               COMMENT '複勝',
  hon_syoukin        CHAR(5)               COMMENT '本賞金',
  syutoku_syokin     CHAR(5)               COMMENT '収得賞金',
  race_pace_stream   CHAR(2)               COMMENT 'レースペース流れ',
  horse_pace_stream  CHAR(2)               COMMENT '馬ペース流れ',
  corner_4_posi      CHAR(1)               COMMENT '4角コース取り',
  load_file          VARCHAR(20)           COMMENT 'ロードファイル',
  last_update        VARCHAR(20)           COMMENT '最終更新',
  PRIMARY KEY (course_code, year_code, kai, day_code, race_num, umaban)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='SED成績データ';
