CREATE TABLE IF NOT EXISTS T_UKC (
  blood_reg_num              CHAR(8)      NOT NULL COMMENT '血統登録番号',
  uma_name                   VARCHAR(36)           COMMENT '馬名',
  seibetsu_code              CHAR(1)               COMMENT '性別コード',
  moke_code                  CHAR(2)               COMMENT '毛色コード',
  uma_kigo_code              CHAR(2)               COMMENT '馬記号コード',
  chichi_uma_name            VARCHAR(36)           COMMENT '父馬名',
  haha_uma_name              VARCHAR(36)           COMMENT '母馬名',
  hahachichi_name            VARCHAR(36)           COMMENT '母父馬名',
  birthdate                  CHAR(8)               COMMENT '生年月日',
  chichi_birth_year          CHAR(4)               COMMENT '父馬生年',
  haha_birth_year            CHAR(4)               COMMENT '母馬生年',
  hahachichi_birth_year      CHAR(4)               COMMENT '母父馬生年',
  umanushi_name              VARCHAR(40)           COMMENT '馬主名',
  umanushi_code              CHAR(2)               COMMENT '馬主会コード',
  seisansha_name             VARCHAR(40)           COMMENT '生産者名',
  sanchi_name                CHAR(8)               COMMENT '産地名',
  massho_flag                CHAR(1)               COMMENT '登録抹消フラグ',
  data_ymd                   CHAR(8)               COMMENT 'データ年月日',
  chichi_keitou_code         CHAR(4)               COMMENT '父系統コード',
  hahachichi_keitou_code     CHAR(4)               COMMENT '母父系統コード',
  load_file                  VARCHAR(20)           COMMENT 'ロードファイル',
  last_update                VARCHAR(20)           COMMENT '最終更新',
  PRIMARY KEY (blood_reg_num)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='UKC馬マスタ';
